var express = require('express')
var app = express()
var bodyParser = require("body-parser")
//var router = express.Router()
var router = require("./router")
//var mysql = require('mysql')
//app.use(router)
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended:true}))
app.use(router)
app.listen(3000, function(){
	console.log('服务启动')
})
